version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-companies
    ports:
      - '6500:5432'
    volumes:
      - postgresCompaniesDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis-companies
    ports:
      - '6379:6379'
    volumes:
      - redisCompaniesDB:/data
volumes:
  postgresCompaniesDB:
  redisCompaniesDB:
